# mkdocs.yml configuration
site_name: My Project Documentation
site_url: https://example.com/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
    - Advanced Usage: user-guide/advanced-usage.md
  - API Reference:
    - Authentication: api-reference/authentication.md
    - Endpoints: api-reference/endpoints.md
  - About:
    - Changelog: about/changelog.md
    - Contributing: about/contributing.md